items:
  spawner-pickaxe:
    material: GOLDEN_PICKAXE
    name: "&#FFD700‚ö° –≠—Ñ–∏—Ä–Ω—ã–π –≠–∫—Å—Ç—Ä–∞–∫—Ç–æ—Ä"
    lore:
      - "&8‚ñ™ &7–¢–∏–ø: &f–ò–Ω—Å—Ç—Ä—É–º–µ–Ω—Ç"
      - "&8‚ñ™ &7–®–∞–Ω—Å: &e–ó–∞–≤–∏—Å–∏—Ç –æ—Ç –£–¥–∞—á–∏"
      - "&8‚ñ™ &7–ü—Ä–æ—á–Ω–æ—Å—Ç—å: &c–û–¥–Ω–æ—Ä–∞–∑–æ–≤—ã–π"
      - ""
      - "&7–ù–∞–∂–º–∏—Ç–µ &f–ü–ö–ú &7–ø–æ —Å–ø–∞–≤–Ω–µ—Ä—É,"
      - "&7—á—Ç–æ–±—ã –ø–æ–ø—ã—Ç–∞—Ç—å—Å—è –∏–∑–≤–ª–µ—á—å –µ–≥–æ."
    custom-model-data: 0
    settings:
      base-chance: 20.0
      chance-per-luck: 0.5
      fail-bonus: 5.0

  pvp-trap:
    material: PRISMARINE_SHARD
    name: "&#FF0044‚ò† –Ø–∫–æ—Ä—å –ë–µ–∑–¥–Ω—ã"
    lore:
      - "&8‚ñ™ &7–ö–∞—Å—Ç: &f–ù–µ—Ä—É—à–∏–º—ã–π –±–∞—Ä—å–µ—Ä"
      - "&8‚ñ™ &7–†–∞–¥–∏—É—Å: &b8 –±–ª–æ–∫–æ–≤"
      - "&8‚ñ™ &7–î–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å: &b20 —Å–µ–∫—É–Ω–¥"
      - ""
      - "&7–°–æ–∑–¥–∞–µ—Ç –º–µ—Ä—Ç–≤—É—é –∑–æ–Ω—É,"
      - "&7–∏–∑ –∫–æ—Ç–æ—Ä–æ–π &c–µ—â–µ –Ω–∏–∫—Ç–æ"
      - "&c–Ω–µ –≤—ã–±–∏—Ä–∞–ª—Å—è –∂–∏–≤—ã–º..."
      - ""
      - "&#FF0044[ –ù–∞–∂–º–∏—Ç–µ –ü–ö–ú –¥–ª—è –∞–∫—Ç–∏–≤–∞—Ü–∏–∏ ]"
    custom-model-data: 0
    settings:
      radius: 8.0
      duration: 20
      cooldown: 60
      wind-charge-cooldown: 10

  death-clock:
    material: CLOCK
    name: "&#E0AAFF‚è≥ –•—Ä–æ–Ω–æ—Å—Ñ–µ—Ä–∞ –°–ø–∞—Å–µ–Ω–∏—è"
    lore:
      - "&8‚ñ™ &7–¢–∏–ø: &f–ü–∞—Å—Å–∏–≤–Ω—ã–π –∞—Ä—Ç–µ—Ñ–∞–∫—Ç"
      - "&8‚ñ™ &7–≠—Ñ—Ñ–µ–∫—Ç: &a–°–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ –∏–Ω–≤–µ–Ω—Ç–∞—Ä—è"
      - ""
      - "&7–ï—Å–ª–∏ –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ –∏–Ω–≤–µ–Ω—Ç–∞—Ä–µ"
      - "&7–≤–æ –≤—Ä–µ–º—è —Å–º–µ—Ä—Ç–µ–ª—å–Ω–æ–≥–æ —É–¥–∞—Ä–∞:"
      - "&a‚úî –°–ø–∞—Å–∞–µ—Ç –≤–µ—â–∏ –∏ –æ–ø—ã—Ç"
      - "&c‚úñ –õ–æ–º–∞–µ—Ç—Å—è –ø–æ—Å–ª–µ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è"
      - "&c‚úñ –ù–µ —Å–ø–∞—Å–∞–µ—Ç –æ—Ç –ü—Ä–æ–∫–ª—è—Ç–∏—è –£—Ç—Ä–∞—Ç—ã"
    custom-model-data: 103

  random-disenchanter:
    material: PAPER
    name: "&#AA00AAüîÆ –°–≤–∏—Ç–æ–∫ –ó–∞–±–≤–µ–Ω–∏—è (–°–ª—É—á–∞–π–Ω—ã–π)"
    lore:
      - "&8‚ñ™ &7–¢–∏–ø: &f–ú–∞–≥–∏—á–µ—Å–∫–∏–π —Å–≤–∏—Ç–æ–∫"
      - "&8‚ñ™ &7–î–µ–π—Å—Ç–≤–∏–µ: &d–°–ª—É—á–∞–π–Ω–æ–µ –∏–∑–≤–ª–µ—á–µ–Ω–∏–µ"
      - ""
      - "&7–ò—Å–ø–æ–ª—å–∑—É–π—Ç–µ –≤ —Å—Ç–æ–ª–µ —á–∞—Ä (/disenchant)"
      - "&7—á—Ç–æ–±—ã —Å–Ω—è—Ç—å &d–æ–¥–∏–Ω —Å–ª—É—á–∞–π–Ω—ã–π &7—á–∞—Ä"
      - "&7–∏ –ø–æ–º–µ—Å—Ç–∏—Ç—å –µ–≥–æ –≤ –∫–Ω–∏–≥—É."
    custom-model-data: 101

  select-disenchanter:
    material: PAPER
    name: "&#00AAFFüìú –°–≤–∏—Ç–æ–∫ –ò–∑–≤–ª–µ—á–µ–Ω–∏—è (–í—ã–±–æ—Ä)"
    lore:
      - "&8‚ñ™ &7–¢–∏–ø: &f–ú–∞–≥–∏—á–µ—Å–∫–∏–π —Å–≤–∏—Ç–æ–∫"
      - "&8‚ñ™ &7–î–µ–π—Å—Ç–≤–∏–µ: &b–¢–æ—á–µ—á–Ω–æ–µ –∏–∑–≤–ª–µ—á–µ–Ω–∏–µ"
      - ""
      - "&7–ò—Å–ø–æ–ª—å–∑—É–π—Ç–µ –≤ —Å—Ç–æ–ª–µ –∑–∞—á–∞—Ä–æ–≤–∞–Ω–∏–π (/disenchant)"
      - "&7—á—Ç–æ–±—ã &b–≤—ã–±—Ä–∞—Ç—å &7–∫–∞–∫–æ–π –∏–º–µ–Ω–Ω–æ"
      - "&7—á–∞—Ä –ø–µ—Ä–µ–Ω–µ—Å—Ç–∏ –≤ –∫–Ω–∏–≥—É."
    custom-model-data: 102

disenchant:
  gui-title: "–ú–∞–≥–∏—á–µ—Å–∫–∏–π —Å—Ç–æ–ª: –ò–∑–≤–ª–µ—á–µ–Ω–∏–µ"
  gui-lore:
    - "&7–ù–∞–∂–º–∏—Ç–µ, —á—Ç–æ–±—ã –∏–∑–≤–ª–µ—á—å:"
    - "&e%enchant%"